crate/crate-qa

setup.py, src/crate/__init__.py
See https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages
For some reasons I got errors running the tests otherwise:
ImportError: Failed to import test module: startup.test_yaml
Traceback (most recent call last):
File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
module = self._get_module_from_name(name)
File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
__import__(name)
File "../crate/crate-qa/tests/startup/test_yaml.py", line 6, in <module>
from crate.qa.tests import NodeProvider
ModuleNotFoundError: No module named 'crate.qa'
=> Use implicit namespace pkg

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
The `wait_for_active_shards` method could return *before* any
shards/tables had been recovered. This could cause the next `alter
table` statement to fail with a `SchemaUnknownException`
=> Fix a race condition in the BwcTest

tests/bwc/test_upgrade.py
Sometimes the `upgrade_segments` operation didn't work correctly.
`wait_for_active_shards` would timeout in `2.x` because a shard
contained old segment files that were no longer readable.
It seems that changing the number_of_replicas somehow caused this.
It's still unclear why - but since we cannot fix this back in 1.1 we'll
have to do a workaround here.
It also seems to be a race-condition, not something that is generally
broken.
=> Fix timeout error in BwcTest

.travis.yml, src/crate/qa/tests.py, tests/bwc/test_rolling_upgrade.py
the test starts a 3 node cluster with the initial version and inserts
data. then, nodes are upgraded to the next version subsequently. after
each upgraded node, a distributed group by is executed in order to test
that all nodes function correctly and different versions can
communicate.
=> added rolling upgrade tests

.travis.yml, setup.py, tests/bwc/test_upgrade.py
It was broken in these versions
=> Exclude `col_ip` query when running against 2.0 or 2.1

.travis.yml, tests/client_tests/php/run.sh, tests/client_tests/php/test_deallocate.php
By using PHP's PDO/libpq we make sure that DEALLOCATE <prep_stmt_name>
statement are invoked and CrateDB handles them correctly.
=> Added tests to verify DEALLOCATE stmt.

tests/bwc/test_rolling_upgrade.py
Master is already on 3.1 and contains streaming changes.
=> Update rolling-upgrade paths

tests/startup/test_cli.py
This reverts commit ae4038c1f0483ba8f21f2c9d39938c41860d2b46.
Related log does not occure anymore at current CrateDB master due
to the fix made by https://github.com/crate/elasticsearch/pull/150 and https://github.com/crate/crate/pull/7518
=> Revert "Add list for whitelisted startup logs."

tests/bwc/test_upgrade.py
A nightly build with the fix is available.
followup to 479d133cf3ac5bb92ab7bc7077c7c28fa28e966d
=> Re-enable nightly version for testing upgrade paths.

tests/bwc/test_upgrade.py
We've a tarball for 3.0.5 with a fix for the BWC issue.
=> bwc: Test 3.0.x again instead of 3.0.3

setup.py
0.9.0 contains changes that require cr8 to be adapted first.
Behavior is broken by: https://github.com/joke2k/faker/commit/f1653f2c4c9789cc940acf26d49e6ac8eaa5c933#diff-b944d78c99f7307469fdcefdb81c84e3 and cr8 must be adapted appropriately.
=> Nail Faker to latest 0.8.x version.

README.md
pyodbc requires the unixodbc headers for building.
=> Add `unixodbc` dev packages to odbc installation documentation.

tests/client_tests/odbc/test_pyodbc.py
At least on jenkins(centOS) the rowcount is always -1  on write statements and so the 
assertions failed. The tests don’t really require this assertions
as the whole scenario would fail if writes weren’t successful.
=> Don’t assert rowcount on ODBC client test write statements

tests/bwc/test_upgrade.py
We're not making any changes anymore to these releases, so we don't have
to test them.
=> Remove upgrade tests from 0.54 to 2.3

tests/bwc/test_upgrade.py
Upgrading from 1.1.x to the latest nightly (3.2-snapshot) is not supported
because of the incompatible index formats (indices must be recreated).
=> Changed default-template bwc test to test the upgrade from 2.1.x

tests/bwc/test_upgrade.py
The wait_for_active_shards() helper method always waits for an exact 
number of active shards. The test created tables without any concrete
replica settings, resulting in 1 replicas with 3 nodes. Thus the finally
active shard count is 16 instead if 8.
Changed the test to disable replicas in the first place.
=> Fix flaky table settings BWC test

tests/startup/test_cli.py
We can have the case that the latest nightly is the last release.
=> Make -SNAPSHOT part optional in cli StartupTest

tests/startup/test_cli.py
The setting has been removed in 4.0
=> Remove `settings['license']['ident']` query

tests/startup/log4j2_console.properties
Since
https://github.com/crate/crate/commit/2dc777139a10761f6cc195efdcb770a705f3da2f
errors in the logging configuration cause CrateDB to exit on startup.
=> Fix log4j2 config used in test_read_crate_yml

src/crate/qa/tests.py, tests/restart/test_metadata.py, tests/startup/test_cli.py
- Remove unsupported settings on node start
- Remove column type assertion from view test
Default column type names changed in CrateDB 4.0.0, asserting for
the types is not required by the test.
- Don't run enterprise enabled/disabled test on >= 4.0.0
The `license.enterprise` setting was removed on 4.0.0, it is not
possible to disable/enable enterprise features anymore in favour
of a seperate community edition.
=> Add support for CrateDB >= 4.0.0

tests/bwc/test_upgrade.py
This adds `3.3.x` between 2.3 and latest-nightly so that migration logic
on templates is run. Otherwise the test would fail with:
IllegalArgumentException: Index patterns must not be null or empty;
got null
=> Fix test_metadata_compatibility

tests/client_tests/go/setup.sql
They're no longer required with all the compatibility improvements we've
made.
=> Remove pg_type hacks from pgx client tests

src/crate/qa/tests.py, tests/bwc/test_rolling_upgrade.py
Ensure partitions can be created while a rolling upgrade is ongoing.
=> Add partition test cases to rolling upgrade BWC

tests/bwc/test_upgrade.py
For some reason the 2.0 -> 2.1 upgrade path test is sometimes flaky.
Given that these version have been EOL for a long time this simply drops
the test scenario.
=> Remove 2.0 → 3.3 upgrade path tests

setup.py
With asyncpg 0.20 the tests get stuck.
This gets the tests to pass until we've figured out the root cause of
the asyncpg 0.20 issue
=> Nail asyncpg to < 0.20

Jenkinsfile, tests/bwc/test_upgrade.py
This adds a backward compatibility test when using update with returning clause  in a mixed cluster of 4.1 and 4.2 nodes. This test ensures that the previous functionality from 4.1 for update is fully working when a 4.2 node is in the cluster. It also ensures that the use of a returning clause from a 4.2 node yields a meaningful error when used in a cluster with 4.1 nodes.
=> Add bwc tests for returning clause for update query

tests/client_tests/node-postgres/README.rst, tests/client_tests/node-postgres/package-lock.json, tests/client_tests/node-postgres/package.json
This makes the dependency requirement on `pg` less restrictive, instead
of nailing to `7.17.1` it will use the latest version.
So we notice if upstream changes cause incompatibilities with CrateDB.
=> Use newest node-postgres version

tests/client_tests/python/asyncpg/test_asyncpg.py
To verify that binary streaming of record types works with CrateDB
(JDBC switches to text-streaming for records, so we don't have proper
integration tests for that in CrateDB itself)
This needs an update after a nightly with the RowType is out.
=> Select record type in asyncpg tests

tests/bwc/test_rolling_upgrade.py, tests/sqllogic/sqllogictest.py
Row values must be formatted to the given format before the sorting mode is applied (formatting must happen on the original result set).
This fixes test failures against CrateDB >= 4.2, it was succeeding on older versions because older CrateDB versions had some arithmetic type issues. The column type was always dictating the result type which by coincident matched the expected type format of the sqllogic tests.
=> Fix formatting of rows

tests/bwc/test_rolling_upgrade.py
Ensure scalar symbols are correctly streamed and resolved on a
mixed version cluster.
This ensures BWC of the new signature based function registry.
=> Add query using scalars on rolling upgrade BWC test

Jenkinsfile, tests/client_tests/go/Dockerfile
Jenkins has not up-to-date go version installed and thus the client test fail currently.
Use a docker golang image now instead to avoid host/jenkins global installation dependencies.
=> Use docker image for go client tests

tests/bwc/test_rolling_upgrade.py
We had a regression on BWC for aggregations which have a different intermediate input data type than the initial argument type causing aggregation streamed from a 4.1 node to a 4.2 node to not being resolvable. 
This adds the related statement to the rolling upgrade test to ensure that it will correctly work on mixed version clusters.
Relates https://github.com/crate/crate/pull/10557.
=> Add aggregation stmt for rolling upgrade test

Dockerfile, tests/client_tests/go/Dockerfile, tests/client_tests/node-postgres/Dockerfile, tests/client_tests/stock_npgsql/Dockerfile
Some of the dependencies pulled in via pip require to be built and need the python header files
=> Ensure python header files are available in docker images

setup.py, src/crate/qa/tests.py, tests/bwc/test_recovery.py, tests/bwc/test_rolling_upgrade.py
Backport of https://github.com/elastic/elasticsearch/blob/master/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RecoveryIT.java
On jenkins the tests needs much more waiting time than running the tests locally. Also using `assertBusy` would be a good idea instead of using `time.sleep`.
The following tests are excluded from this pr:
- testSoftDeletesDisabledWarning (not relevant)
- testHistoryUUIDIsGenerated (can't retrieve history uuid from the client)
- testAutoExpandIndicesDuringRollingUpgrade (missing https://github.com/elastic/elasticsearch/pull/48974 https://github.com/elastic/elasticsearch/pull/50361 ) 
- testRetentionLeasesEstablishedWhenRelocatingPrimary (retaining seq_no won't update correctly)
- testRetentionLeasesEstablishedWhenPromotingPrimary (retaining seq_no …
=> Recovery Tests Backport

tests/bwc/test_recovery.py
If multiple nodes are upgraded at once while other nodes are still
on older versions, the cluster may not be able to (re-) allocate
all shards (replicas) resulting in a YELLOW cluster health.
Additionally for one test scenario, we must ensure that all replica shards are active before any node
is upgraded. Otherwise the cluster may try to allocate new replica shards if the upgraded node contains the primary shard. This would fail then due to node version based allocation rules (a replica cannot be allocated on a node which has a lower version than the primary).
=> Fix flaky bwc recovery tests by only upgrade 1 node at a time

Jenkinsfile
Sometimes old builds leave traces behind which could break new builds.
(E.g. if a client test switches to a docker build, but some caches
or env vars still exists at the workspace. Did happen for golang tests).
Cleaning up the workspace as a post step should avoid that.
=> Add post workspace cleanup step to jenkins pipeline

tests/client_tests/node-postgres/README.rst, tests/client_tests/node-postgres/backlog.rst, tests/client_tests/node-postgres/db.js, tests/client_tests/node-postgres/main.js, tests/client_tests/node-postgres/package-lock.json, tests/client_tests/node-postgres/package.json, tests/client_tests/node-postgres/test_parameterized_timestamp.js
Hi there,
this adds a test case which outlines a regression discovered with CrateDB 4.3.3, see [1]. With one of the next iterations, we should introduce a real test framework instead of rolling our own, see [2].
With kind regards,
Andreas.
[1] https://gist.github.com/amotl/b25297e7dc5a7f744aebb04ce4960833
[2] https://github.com/crate/crate-qa/blob/91f306/tests/client_tests/node-postgres/backlog.rst
P.S.: This will probably fail until CrateDB 4.3.4 can be used.
=> node-postgres: Add test case for INSERTs with parameterized timestamp

Jenkinsfile
We've had the tests get stuck for days before noticing.
This adds a timeout that's large enough to ensure the tests can finish
if things are working and ensures we notice if things aren't working.
=> Add a timeout to Jenkinsfile

tests/client_tests/stock_npgsql/Dockerfile
Hi there,
jobs like [1] occasionally fail when running the _npgsql client tests_ like
```
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
I have been able to reproduce the error in isolation when just invoking Docker and following the recipe.
```sh
docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:3.1 bash
apt-get update && apt-get -y install python3-venv python3-dev
root@ab9bf88e6209:/# x86_64-linux-gnu-gcc
bash: x86_64-linux-gnu-gcc: command not found
```
So, let's just add the `build-essential` package in order to satisfy the build. Why this apparently was able to succeed from time to time is beyond my imagination.
With kind regards,
Andreas.
[1] …
=> npgsql: Add "build-essential" to list of dependency packages

tests/bwc/test_recovery.py
`retention_leases['leases']` can be null if the leases aren't synced
yet.
This caused a `TypeError` which wasn't catched by the `assert_busy`
routine. So this adds a `assertIsNotNone` check to ensure the
`assert_busy` routine re-tries until the sync happened.
This replaces https://github.com/crate/crate-qa/pull/183
=> Fix TypeError in _assert_ensure_peer_recovery_retention_leases_renewed_and_synced

tests/bwc/test_hotfix_downgrades.py
-  Fix hotfix downgrade test to include downgrade paths to X.X.0 versions.
Due to this bug, the test did not run e.g. on the downgrade path 4.4.1 -> 4.4.0
-  Skip hotfix downgrade path at is currently expected to fail
All CrateDB versions < 4.4.3 won't support allocation of shards
on nodes with lower hotfix version.
See crate/crate#11103.
We must re-enable this, once we have versions published including
this fix.
=> Fix hotfix downgrade test and mark it as skipped

tests/bwc/test_recovery.py
The test inside the RecoveryTest suite are failing occasionally.
Until this is fixed, they are disabled in order to let all other
tests run. Otherwise possible other issues won't pop up anymore.
=> Disable bwc.test_recovery test suite until flakyness is solved

tests/client_tests/python/asyncpg/test_asyncpg.py
To verify the binary encoding/decoding in CrateDB works.
This will require a nightly build including https://github.com/crate/crate/pull/11355
=> Add bit encoding test using asyncpg

src/crate/qa/tests.py, tests/bwc/test_recovery.py, tests/snapshot/test_snapshot.py
Relates to https://github.com/crate/crate/pull/11820
Inspired by https://github.com/elastic/elasticsearch/commit/1064009e9d967bd9e81e10f4eb8dd33808ec1762#diff-b14376ec9051ae5d30b80f77846aefdc262eb791876f50c55193908e4a818f05R524
See individual commits.
=> Add test for parallel drop and restore for snapshots

Jenkinsfile, tests/client_tests/haskell/src/Main.hs, tests/client_tests/haskell/stack.yaml, tests/client_tests/haskell/stack.yaml.lock, tests/client_tests/odbc/test_pyodbc.py, tests/kafka-connect-jdbc/gradle/wrapper/gradle-wrapper.properties
JDK11 is available on the slaves and some of the jobs even don't need a
JDK because they're using the bundled JDK in CrateDB
I think BWC test failure is a real issue - not related to the infrastructure changes. I'd like to merge the rest so that everything else works again.
=> Update Jenkinsfile/tests for infrastructure changes

Jenkinsfile, tests/client_tests/haskell/Dockerfile, tests/client_tests/haskell/stack.yaml, tests/client_tests/haskell/stack.yaml.lock
The default image seems to miss `pg_conf` which is required to build the
postgresql clients used in the tests
Force pushing too often seems to have broken the status reporting - test result is here: https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/34/pipeline/36
=> Use custom docker image for haskell tests

src/crate/qa/tests.py
Follow up to https://github.com/crate/crate/pull/12463
Fixes https://github.com/crate/crate-alerts/issues/249
=> Reflect node.max_local_storage_nodes setting removal

tests/client_tests/odbc/test_pyodbc.py
resolves https://github.com/crate/crate-alerts/issues/261
follow up to https://github.com/crate/crate/pull/12565
From https://www.postgresql.org/docs/current/datatype-datetime.html:
>In a literal that has been determined to be timestamp without time zone, PostgreSQL will silently ignore any time zone indication
=> reflect change of the timestamp alias to timestamp without time zone

tests/client_tests/odbc/test_pyodbc.py
Requires https://github.com/crate/crate/pull/12724
=> Add test case for `bit` insert/select with pyodbc

.gitignore, README.md
- Add `venv` to git ignore
- Update `README` to use generic `python3` alias of activated virtual env instead of specific binary like `python3.6`.
=> Update .gitginore and README

tests/client_tests/rust/Cargo.lock, tests/client_tests/rust/Cargo.toml, tests/client_tests/rust/src/main.rs
Try to fix rust client failures:
- Update postgres dependency to latest stable version
- Add some code to printout the failure when creating the prepared stmt
=> Fix rust client failures

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
`upgrade_segments` is deprecated starting from CrateDB 5.1 (https://github.com/crate/crate/pull/12810/)
It seems this option was used for 1.1.x (see https://github.com/crate/crate-qa/commit/e5e2ec532299bf6e080c074617e8ec2ff94b65bf#diff-da22f73840f87231551db9d0b0f9c4592e94b91a66208f3a45935705d162a617R19)
and 2.3.x (see https://github.com/crate/crate-qa/pull/36/files#diff-da22f73840f87231551db9d0b0f9c4592e94b91a66208f3a45935705d162a617R24)
But then we removed those versions in https://github.com/crate/crate-qa/pull/84/ - so we don't need this
=> remove upgrade_segments usages

tests/client_tests/stock_npgsql/stock_npgsql.csproj
Npgsql 7 has been released [^1], and is currently at 7.0.2.
- https://www.nuget.org/packages/Npgsql/
- https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL
- https://www.nuget.org/packages/Microsoft.EntityFrameworkCore
[^1]: https://www.npgsql.org/doc/release-notes/7.0.html
=> Npgsql: Update to Npgsql 7

.gitignore, setup.py, tests/client_tests/python/asyncpg/test_asyncpg.py, tests/client_tests/python/psycopg3/test_psycopg3.py
This patch adds test cases for `psycopg3` [1,2]. In the same spirit as the test cases for `asyncpg`, it uses the asynchronous mode of the library. The difference between both test case files can be inspected at [3].
[1] https://www.psycopg.org/psycopg3/docs/
[2] https://github.com/psycopg/psycopg
[3] https://gist.github.com/amotl/8ee866bf204c5c5ee4bad463ec3660a0
=> Python: Add test cases for psycopg3

tests/bwc/test_upgrade.py
To ease the investigation of logs in case of failure, truncate the cluster logs after every run of `_do_upgrade` (testing a single version upgrade path, e.g. 5.1 -> 5.2)
Also increase the method timeout to 5 mins.
Relates: #244
=> Truncate cluster logs after every `test_upgrade_paths` run

Jenkinsfile
Since each of the bwc tests takes quite some time to execute
split them into stages to make them run in parallel.
=> Split bwc tests to run in parallel

setup.cfg, tests/client_tests/python/asyncpg/test_asyncpg.py, tests/client_tests/python/psycopg3/test_psycopg3.py
This patch brings [`unittest.IsolatedAsyncioTestCase`](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) to the asyncpg and psycogp3 test cases, as suggested. Thanks!
=> Python: Use `unittest.IsolatedAsyncioTestCase` for asyncpg and psycogp3 test cases

tests/bwc/test_upgrade.py
There seems to be an issue in 4.4/4.5 where
`container.put(BytesIO(b'sample data'))` gets stuck if the shards are
not allocated.
Given that we can't fix this in those versions, this adds a check for
green after creating the table.
=> Assert green after creating blob table in bwc tests

tests/client_tests/stock_npgsql/Program.cs
Add DROP TABLE statements to allow for multiple runs against a CrateDB instance, when locally testing/debugging.
=> Add DROP TABLE statements to npgsql client test

tests/bwc/test_rolling_upgrade.py
The rolling upgrade tests are also flaky, sometimes getting stuck with a
`select count(*) from sys.shards where state = 'STARTED'` on the 4.4.0
upgrade step.
This change is mostly to rule out the threading deadlock mentioned in
https://github.com/crate/crate-qa/commit/cc3efd5ec3c24bc0fb0f7906dabc6f27462caaa1
as a reason. There are no blobs involved in the rolling upgrade, so this
likely doesn't fix it.
---
If this doesn't work out we may have to wrap `cursor.execute` calls into a thread and apply a timeout + retry.
=> Set worker count for rolling upgrade tests

Dockerfile
openjdk-11-jdk is no longer available in the bookworm repositories
=> Update JDK from 11 to 17 in Dockerfile for rust tests

setup.py
It contains handling for maven as build system
when using source path or ``branch:<name>`` as target version.
https://github.com/mfussenegger/cr8/commit/fcd8161265bc0841058ab9f86e63eba6df6702ff
Useful for local debugging when replacing 
ROLLING_UPGRADES to smth like
```
ROLLING_UPGRADES = (
UpgradePath('5.4.x', '/path-to-crate-repo'),
)
```
=> Bump cr8 version to 0.24.0

Jenkinsfile, setup.py
argh has released 0.30.0 which currently leads to failures:
```
argh.exceptions.AssemblingError: argument "hosts" declared as positional (in function signature) and optional (via decorator)
```
=> Pin argh to 0.29.4

tests/bwc/test_upgrade.py
Since CrateDB 5.5.0, the CREATE TABLE statement is more strict and does not allow anymore to use unqualified names in place of string literals to define values within WITH clauses. See https://cratedb.com/docs/crate/reference/en/master/appendices/release-notes/5.5.0.html#sql-statements
Relates the failure seen at #285.
=> Fix CREATE TABLE stmt used at the upgrade test

tests/bwc/test_rolling_upgrade.py
Ensure writes to non-partitioned tables are working while running a mixed version cluster by upserting a row on each upgrade path.
Closes #271.
=> Write to normal table on rolling upgrade test

tests/client_tests/go/Dockerfile
Maintenance update to use the most recent stable version of Golang 1.21 for the [pgx](https://github.com/jackc/pgx) tests.
=> Update to Golang 1.21

tests/client_tests/haskell/stack.yaml, tests/client_tests/haskell/stack.yaml.lock
Follows https://github.com/crate/crate-qa/pull/293
Stack bootstraps GHC, so the docker image change likely didn't really
have any effect at all. (Other than possibly using a newer stack
version)
=> Update stack resolver for haskell client tests

tests/client_tests/stock_npgsql/Dockerfile, tests/client_tests/stock_npgsql/run.sh, tests/client_tests/stock_npgsql/stock_npgsql.csproj
Maintenance update to use the most recent version of the [.NET data provider for PostgreSQL](https://www.npgsql.org/).
It is [version 8.0.0](https://github.com/npgsql/npgsql/releases/tag/v8.0.0), which has been released last week.
=> Update to Npgsql 8.0.1 and .NET 8

tests/client_tests/stock_jdbc/build.gradle, tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java
Maintenance update to use the most recent version of the [PostgreSQL JDBC Driver](https://jdbc.postgresql.org/).
[Version 42.7.0](https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.0) was released in November 2023. [Version 42.7.1](https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.1) was released in December 2023. 
- https://github.com/crate/cratedb-examples/pull/191
- https://github.com/crate/crate/issues/15113
=> Update to pgjdbc 42.7.1

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
On CI the upgrade testcase is flaky, failing because it cannot form a
cluster within the timeout.
This is just a shot in the dark - the theory is that there are timing
issues updating the eligible masters. Setting them explicitly should
help mitigate it.
=> Set seed_nodes and initial_master_nodes explicit

tests/bwc/test_rolling_upgrade.py, tests/bwc/test_upgrade.py
=> Test 4.0.x -> latest-nightly path in test_snapshot_compatibility

tests/bwc/test_upgrade.py
Add timestamp to each upgrade step, to be able to check timeout failures.
=> Improve time tracking of upgrade paths

Dockerfile, tests/client_tests/go/Dockerfile, tests/client_tests/haskell/Dockerfile, tests/client_tests/node-postgres/Dockerfile, tests/client_tests/stock_npgsql/Dockerfile
Jenkins calls docker like with a user mapping to the runner's user id:
docker run -t -d -u 1001:1001 -w ...
If the user doesn't exist in the image, the fs permissions are messed
up, which caused issues after trying to upgrade the GraalVM polyglot
package in CrateDB. See https://github.com/crate/crate/pull/15769
Adding a jenkins user to the images should fix this.
=> Add jenkins user to docker images

tests/client_tests/rust/Cargo.lock
Update dependencies in `tests/client_tests/rust/Cargo.lock`.
Two admonitions by Dependabot.
https://github.com/crate/crate-qa/security/dependabot
```shell
docker run --rm -it --volume=$(PWD):/src rust bash
cd /src
cargo update
```
=> Client Tests: Update dependencies for Rust, using `cargo update`

tests/bwc/test_upgrade.py
From recently added logs it seems that the longest upgrade path, (starting with `4.0.x`), frequently consumes a bit more than 10 mins.
example failure: https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa/detail/crate_qa/793/pipeline
=> Increase timeout per upgrade path to 15mins

tests/bwc/test_upgrade.py
`crate-qa` periodically times out while running `test_upgrade.StorageCompatibilityTest`.
Possible fix for https://github.com/crate/crate-alerts/issues/735
=> Increase timeout on StorageCompatibilityTest

tests/bwc/test_upgrade.py
Adding a test for https://github.com/crate/crate/pull/17580.
=> Test dynamic column names in resultsets

tests/bwc/test_upgrade.py
=> Revert #344

tests/bwc/test_upgrade.py
Improves https://github.com/crate/crate-qa/pull/344.
=> Test dynamic column names in resultsets with less partitions created

tests/client_tests/go/Dockerfile
Seems to resolve the issue with missing package:
https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa/detail/crate_qa/1237/pipeline/39#step-198-log-148
```
=====
basic_queries.go:10:2: no required module provides package github.com/jackc/pgx/v5; to add it:
go get github.com/jackc/pgx/v5
Failure running: go run ./basic_queries.go --hosts 127.0.0.1 --port 5432
script returned exit code 1
```
=> Update go docker image to 1.24

tests/bwc/test_rolling_upgrade.py
Originate from https://github.com/crate/crate-qa/issues/341. Adds metadata rolling upgrade tests - privileges, views, default expressions, generated columns and constraints. Also partitioned table with aforementioned columns and table/partition versions.
=> Improve metadata bwc tests

tests/bwc/test_upgrade.py
Integration and cross-version test for https://github.com/crate/crate/pull/17819
=> Add upgrade test to ensure oid-less doc references load correctly

.gitignore, tests/client_tests/stock_jdbc/build.gradle, tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java, tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcTest.java
[pgjdbc 42.7.5](https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.5) has been released yesterday. When running the stock jdbc test cases, [errors can be observed on Jenkins](https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/473/pipeline/41/#step-298-log-122) after bumping manually per this PR.
Validating an automatic Dependabot update [failed over here on GHA](https://github.com/crate/cratedb-examples/actions/runs/12781092084/job/35678627382?pr=804#step:8:1780), apparently tripping test_getFunctions, test_getColumns, test_getPrimaryKeys, and test_getTables in `JdbcMetaDataTest.java`.
- https://github.com/crate/cratedb-examples/pull/804
/cc @kneth, @seut
=> JDBC: Update to pgjdbc 42.7.7

tests/client_tests/node-postgres/Dockerfile
```
1 warning found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 9)
Dockerfile:3
```
See: https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa/detail/crate_qa/1300/pipeline/43
=> Fix Dockerfile for nodejs tests: use new format for ENV

Jenkinsfile, tests/client_tests/node-postgres/Dockerfile
`buster` seems to no longer be available:
```
> [2/3] RUN   groupadd jenkins &&   useradd -u 1001 -g jenkins -m jenkins &&   apt-get update &&   apt-get -y install python3-pip libpq5 libpq-dev sudo:
0.235 Ign:1 http://security.debian.org/debian-security buster/updates InRelease
0.236 Ign:2 http://deb.debian.org/debian buster InRelease
0.282 Err:3 http://security.debian.org/debian-security buster/updates Release
0.282   404  Not Found [IP: 146.75.122.132 80]
0.283 Ign:4 http://deb.debian.org/debian buster-updates InRelease
0.309 Err:5 http://deb.debian.org/debian buster Release
0.309   404  Not Found [IP: 146.75.122.132 80]
0.332 Err:6 http://deb.debian.org/debian buster-updates Release
0.332   404  Not Found [IP: 146.75.122.132 80]
0.334 Reading package lists...
0.344 E: The repository …
```
=> Fix nodejs tests update image buster->trixie (latest debian stable)

tests/client_tests/node-postgres/cratedb.test.js
The test emitted warnings because the connection pool wasn't closed:
Jest did not exit one second after the test run has completed.
'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
See https://node-postgres.com/apis/pool#poolend
=> Fix connection leak in node-postgres client tests

tests/bwc/test_rolling_upgrade.py
Example failure:
```
FAIL: test_rolling_upgrade_5_to_6 (test_rolling_upgrade.RollingUpgradeTest.test_rolling_upgrade_5_to_6) [6.0.x -> latest-nightly]
----------------------------------------------------------------------
Traceback (most recent call last):
File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/tests/bwc/test_rolling_upgrade.py", line 68, in test_rolling_upgrade_5_to_6
self._test_rolling_upgrade(path, nodes=3)
File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa/tests/bwc/test_rolling_upgrade.py", line 230, in _test_rolling_upgrade
self.assertEqual(res[0][0], 'matchMe title')
AssertionError: 'no match title' != 'matchMe title'
- no match title
? ---
+ matchMe title
?      ++
```
=> Add missing refresh statement

tests/bwc/test_rolling_upgrade.py
For debugging purposes, to understand why the assertion is failing (duplicate rows? order by returning them in inverse order?)
=> Add printout for results of match query
