.travis.yml, README.md, setup.py, tests/bwc/test_upgrade.py
one range from 0.54 -> 2.3, and one from 2.2 -> latest
=> multiple upgrade paths for bwc tests

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
* users
* privileges
* user defined functions
Requires a nightly release of https://github.com/crate/crate/commit/d0cca6fbaae63a57beb778b00e3da9a5df3f05ef
=> added upgrade tests for custom meta data

tests/bwc/test_upgrade.py
The retry was added because the wait_for_active shards check collects the shard
information directly from the nodes. The internal ES code, however, retrieves
the shard information from the ClusterState. A retry is necessary in case the
shards are ready but the cluster state hasn't been updated yet.
=> Add retry for optimize to tolerate stale cluster states

tests/startup/test_cli.py
See https://github.com/crate/crate/commit/435599c789ecb6a7c6823be33740509a235bf84b
=> Adapt tests to exception message change in CrateDB

tests/bwc/test_upgrade.py
to ensure metadata and data is persisted also with latest/upcoming
version
=> restart latest cratedb version in BWC tests

tests/client_tests/go/bulk_operations.go, tests/client_tests/go/run.sh, tests/client_tests/go/setup.sql
requires https://github.com/crate/crate/pull/7431 to be merged and released in nightly build
=> add bulk insert test with Golang pgx client

tests/client_tests/go/basic_queries.go, tests/client_tests/go/setup.sql
The fix for the timestamp column depends on https://github.com/crate/crate/pull/7494
=> Avoid errors when using pgx and add timestamp column test.

tests/startup/test_cli.py
Some startup logs do not contain a node name e.g:
```
[2018-06-26T11:45:16,280][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
```
This log is output if: `io.netty.noUnsafe=true` is set, which it is in: https://github.com/crate/crate/blob/master/app/src/bin/crate.in.sh#L107
Rather than suppressing this log, it is being whitelisted as an accepted log entry in this pr.
=> Whitelist certain startup logs 

setup.py, tests/bwc/test_rolling_upgrade.py, tests/bwc/test_upgrade.py
See https://github.com/mfussenegger/cr8/pull/260
=> Test unreleased changes in stable branch in bwc tests

tests/bwc/test_upgrade.py
Add test to verify that tables created with a setting which is not
supported anymore on versions > 2.3.x, will still be usable on latest
version.
=> Add table settings compatibility test

tests/client_tests/haskell/crate-qa-hask.cabal, tests/client_tests/haskell/src/Main.hs, tests/client_tests/haskell/stack.yaml
Depends on crate/crate#7902
(Will merge this once a nightly with the fix above is out)
=> Extend hasql client tests with text encoding/decoding

tests/bwc/test_upgrade.py
This exposes issues with the template updates on schema changes.
=> Extend bwc tests to create dynamic columns and partitions

tests/restart/test_metadata.py
We added the `AL` privilege in CrateDB master
=> Update privileges test to account for new privileges

src/crate/qa/minio_svr.py, src/crate/qa/tests.py, tests/bwc/test_upgrade.py
The case where there is version diversity within a cluster is missing.
Just wanted to check this in to get feedback on whether I am heading in the correct direction.
=> Test snapshot compatibility between versions also within same cluster

.gitignore, Jenkinsfile, tests/client_tests/node-postgres/Dockerfile, tests/client_tests/node-postgres/README.rst, tests/client_tests/node-postgres/app.js, tests/client_tests/node-postgres/csv.js, tests/client_tests/node-postgres/db.js, tests/client_tests/node-postgres/package-lock.json, tests/client_tests/node-postgres/package.json, tests/client_tests/node-postgres/resources/log_entries.csv, tests/client_tests/node-postgres/run.sh
A nodejs application showcasing a test interaction with CrateDB.
Staring the node-postgres module as middleware. 
The interaction:
1. Opens a connection pool with CrateDB.
2. Creates a table
3. Inserts 10000 log entries, which are recovered from a csv file
4. Checks that all data have been loaded.
5. Updates log entries whose object size is 0, to make it 40 for no
particular reason.
6. Checks that the returning clause yields the updated data, with
the expected count of rows.
7. Drops the table
8. Closes the connection pool.
9. Exits the node process.
=> CrateDB client tests for nodejs/node-postgres

Jenkinsfile, src/crate/qa/tests.py, tests/bwc/test_rolling_upgrade.py, tests/bwc/test_upgrade.py
=> Improve tests

tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java
=> Update JDBC metadata tests to reflect supported functions

tests/bwc/test_upgrade.py
Test for bwc for returning-for-insert. Won't work until https://github.com/crate/crate/pull/9624 is merged to master. I checked it locally against the branch, and it is passing.
=> Add returning for insert bwc test

tests/kafka-connect-jdbc/run.sh
=> Set directory for kafka-test script and test for docker-image

tests/bwc/test_recovery.py
This test ensures that replicas are auto-expanding according to the allocation filtering rules. Since versions < 4.4 of nodes do not have the related bp (https://github.com/crate/crate/pull/10734 ) implemented, these nodes would not be filtered at all. Therefore this can only be tested from 4.4 forwards. For this reason the test is not an exact port from the original version from https://github.com/elastic/elasticsearch/blob/master/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RecoveryIT.java but instead focuses on covering the filter application while going through an upgrade of a cluster. 
Once 4.4 is released this would serve as a starting point to upgrade to the newer versions.
=> Add allocation filtering recovery test

tests/bwc/test_recovery.py
This adds backports of the two retention leases related recovery tests from `RecoveryIT.java`:
- test_retention_leases_established_when_promoting_primary
https://github.com/elastic/elasticsearch/blob/master/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RecoveryIT.java#L328
- test_retention_leases_established_when_relocating_primary
https://github.com/elastic/elasticsearch/blob/master/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RecoveryIT.java#L350
Note:
This only works with soft deletes disabled, we are missing some more recent backports.
=> Add retention leases related recovery tests

tests/bwc/test_recovery.py
=> Unflake recovery test

tests/bwc/test_recovery.py
This test was doing wrong assumption and was also not testing any
upgrade as the upgrade path was on same versions (latest/4.4).
The test should only test expected behaviour on upgrades from
any version to 4.4.
=> Fix `test_auto_expand_indices_during_rolling_upgrade` bwc test 

tests/client_tests/stock_npgsql/Program.cs
See https://github.com/crate/crate/issues/10776
Requires nightly with https://github.com/crate/crate/pull/10780
=> Add insert-unnest test-case to npgsql tests

tests/client_tests/python/asyncpg/test_asyncpg.py
Hi there,
this patch is just a slight refactoring in order to bring in more test cases afterwards. It does not bring in any semantic changes.
With kind regards,
Andreas.
=> asyncpg: Slightly refactor test layout

tests/client_tests/python/asyncpg/test_asyncpg.py
Hi again,
this patch streamlines the invocation routines to accept a database URI.
When this URI can be obtained from an environment variable `CRATEDB_URI`, the machinery does not invoke a CrateDB layer through `cr8`'s `crate.qa.tests.NodeProvider`.
This tremendously helps when running on macOS when CrateDB is already running within a Docker container and speeds up the whole testing cycle. I've used it for getting hold of #191.
With kind regards,
Andreas.
=> asyncpg: Provide an option to run the test suite without cr8

tests/client_tests/stock_npgsql/Dockerfile, tests/client_tests/stock_npgsql/Program.cs, tests/client_tests/stock_npgsql/run.sh, tests/client_tests/stock_npgsql/stock_npgsql.csproj
Requires https://github.com/crate/crate/pull/12044
=> Add entity framework insert test for npgsql

tests/bwc/test_rolling_upgrade.py
=> fix 4.3-4.4 upgrade path

tests/client_tests/odbc/test_pyodbc.py, tests/client_tests/python/asyncpg/test_asyncpg.py
Resolves https://github.com/crate/crate-alerts/issues/283
=> fix table function name

tests/sqllogic/test_sqllogic.py
Use new custom queries from sqllogictests
Relates: https://github.com/crate/sqllogictest/pull/1
=> Use new custom queries from sqllogictests

tests/client_tests/stock_jdbc/build.gradle, tests/kafka-connect-jdbc/build.gradle
closes https://github.com/crate/crate-alerts/issues/354
=> don't use deprecated jcenter repo

Jenkinsfile, tests/client_tests/go/Dockerfile, tests/client_tests/go/basic_queries.go, tests/client_tests/go/bulk_operations.go, tests/client_tests/go/run.sh, tests/client_tests/python/asyncpg/test_asyncpg.py
relates to https://github.com/crate/crate-alerts/issues/354
See commit messages
=> Fix go and python client tests

tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java
Fixes https://github.com/crate/crate-alerts/issues/425
=> Bump PG version to 11.0

tests/bwc/test_upgrade.py
Help to investigate failures of `test_upgrade_paths` runs by exposing the cluster logs.
Relates: #244
=> Include cluster logs in case of error for test_upgrade_paths

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
-  Wrap the upgrade process in a timeout decorator to also print
the cluster logs in case of a timeout.
Relates to https://github.com/crate/crate-qa/issues/244
=> Use timeout for every upgrade on versions path

tests/bwc/test_upgrade.py
Increase timeout from 5 to 7 mins
=> Increase timeout for _do_upgrade

tests/client_tests/python/psycopg3/test_psycopg3.py
Following up on GH-248, this adds another test case using server-side cursors (portals) [^1] with CrateDB. The single difference between `fetch_summits_client_cursor`, and the new `fetch_summits_server_cursor` test case, is the additional `name` argument to the cursor factory method:
```python
async with conn.cursor(name="foo") as cursor:
^
```
[^1]: https://www.psycopg.org/psycopg3/docs/advanced/cursors.html#server-side-cursors
=> Python: Add psycopg3 test case using a server-side cursor (portal)

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
Otherwise all nodes of a cluster write to the same file
Relates to: https://github.com/crate/crate-qa/issues/244
=> Use dedicated log dir per node in bwc tests

tests/bwc/test_upgrade.py
Just to ensure the cluster formed
=> Assert cluster size in BWC upgrade tests

tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java
Relates: https://github.com/crate/crate/issues/13418
=> Update expected PostgreSQL version to 14

tests/bwc/test_rolling_upgrade.py
Relates to https://github.com/crate/crate/pull/14026
=> Check MATCH queries on rolling upgrades

tests/client_tests/stock_jdbc/build.gradle
For handling of new tarball contents format
=> Bump crate-testing to 0.11.1

tests/bwc/test_rolling_upgrade.py
Dynamically added empty arrays and ignored object sub-columns are indexed with special prefix starting from 5.5 Ensure that reading such columns work across all versions.
Related to https://github.com/crate/crate/commit/278d45f176e7d1d3215118255cd69afd2d3786ee
=> Create dynamically an empty array and ignored object sub-column

tests/bwc/test_upgrade.py
Also makes the default test output a bit more verbose - showing the upgrade path permutations:
```
Start version: 4.1.x
Upgrade to: 4.2.x
Upgrade to: 4.3.x
Upgrade to: 4.4.x
Upgrade to: 4.5.x
Upgrade to: 4.6.x
Upgrade to: 4.7.x
Upgrade to: 4.8.x
Upgrade to: 5.0.x
Upgrade to: 5.1.x
Upgrade to: 5.2.x
Upgrade to: 5.3.x
Upgrade to: 5.4.x
Upgrade to: 5.5.x
Upgrade to: latest-nightly
Start version: 4.2.x
Upgrade to: 4.3.x
Upgrade to: 4.4.x
-
```
=> Ensure users persist across version upgrades

tests/bwc/test_upgrade.py
=> Ensure privileges persist across version upgrades

tests/bwc/test_rolling_upgrade.py
To catch regressions like https://github.com/crate/crate/pull/15425 in
the future
=> Ensure user exists before rolling upgrade

src/crate/qa/tests.py, tests/bwc/test_upgrade.py
Also increase cratedb heap size to 1GB, see commits.
=> Ensure all nodes are up & discovered in upgrade bwc tests

tests/bwc/test_upgrade.py
Fixes https://github.com/crate/crate-qa/issues/305
=> Bump timeout to 10 mins; add timestamps to log lines

setup.py
https://github.com/mfussenegger/cr8/commit/a053e80bc43dd5e584b14529f54dcacca22207a3
=> Bump cr8 to 0.26.0

setup.py
=> Revert "Bump cr8 to 0.26.0"

tests/bwc/test_rolling_upgrade.py
Catches regression caused by https://github.com/crate/crate/commit/0653a1f99fbb14574d607e90f4a5523726ff7479
=> Add sys.nodes query to rolling upgrade test

tests/bwc/test_recovery.py, tests/bwc/test_rolling_upgrade.py, tests/bwc/test_upgrade.py
=> Add CrateDB 5.9.0 to BWC tests

tests/bwc/test_upgrade.py
Follow up of d18f4162fd8e124747db2e03aba50651feb5d694.
=> Fix flake8 style issue

tests/bwc/test_rolling_upgrade.py
Relates to https://github.com/crate/crate/pull/16884
=> Execute a query as a custom user

tests/bwc/test_upgrade.py
Some logic in CrateDB is table version specific, this helps cover more
mixed table version scenarios.
=> Create new table on each version during BWC upgrade tests

tests/client_tests/stock_jdbc/build.gradle, tests/client_tests/stock_jdbc/src/test/java/stock_jdbc/JdbcMetaDataTest.java
* upgrade to latest PG JDBC driver
* updating link to issue in one test
=> [stock JDBC] update to PG JDBC 42.7.4

setup.py, tests/bwc/test_partition_storage_formats.py
Tests for https://github.com/crate/crate/pull/17041
=> Add test for per-partition stored-field format

tests/bwc/test_rolling_upgrade.py
Test for https://github.com/crate/crate/pull/17492.
=> Ensure UDFs are loaded before rolling upgrade

tests/bwc/test_upgrade.py
To catch upgrade issues on unreleased hotfixes too
=> Add 5.10 branch to upgrade tests
